### ISSUE TITLE
Error when trying to show lock info in a locked file

### ISSUE THREAD

**Issue by federico-s** [zielu/SVNToolBox#23]
When I click in the "Show Lock Info" in the Subversion menu, if the file is locked it displays the following error:

`null
java.lang.AssertionError
	at com.intellij.ui.popup.AbstractPopup.show(AbstractPopup.java:743)
	at com.intellij.ui.popup.AbstractPopup.showInCenterOf(AbstractPopup.java:390)
	at com.intellij.ui.popup.AbstractPopup.showInFocusCenter(AbstractPopup.java:500)
	at zielu.svntoolbox.ui.actions.ShowLockInfoTask.run(ShowLockInfoTask.java:126)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

If the file is not locked, everything is going well.

**Comment by zielu** [comment]
@federico-s It happens in Idea 2017 right ?

**Comment by federico-s** [comment]
Yep, on a Mac

Il 26 feb 2018 21:46, "Łukasz Zieliński" <notifications@github.com> ha
scritto:

**Comment by zielu** [comment]
Fixed in 173.0.2
