### ISSUE TITLE
Intellij 2018.3 Issue with SVNToolBox-183.1.0.jar!/META-INF/java-features.xml

### ISSUE THREAD

**Issue by Ceddaerrix** [zielu/SVNToolBox#27]
Starting Intellij 2018.3 with the SVNToolBox plugin logs the following error:

`2019-02-21 14:11:45,189 [   2262]   INFO - llij.ide.plugins.PluginManager - Cannot load C:\Users\my-user\.IntelliJIdea2018.3\config\plugins\SVNToolBox\lib\SVNToolBox-183.1.0.jar!/META-INF/java-features.xml 
org.jdom.JDOMException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
	at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:229)
	at com.intellij.openapi.util.JDOMUtil.load(JDOMUtil.java:295)
	at com.intellij.ide.plugins.PluginManagerCore.loadDescriptorFromJar(PluginManagerCore.java:690)
	at com.intellij.ide.plugins.PluginManagerCore.loadDescriptor(PluginManagerCore.java:785)
	at com.intellij.ide.plugins.PluginManagerCore.lambda$loadDescriptor$2(PluginManagerCore.java:798)
	at com.intellij.ide.plugins.PluginManagerCore.resolveOptionalDescriptors(PluginManagerCore.java:887)
	at com.intellij.ide.plugins.PluginManagerCore.loadDescriptor(PluginManagerCore.java:795)
	at com.intellij.ide.plugins.PluginManagerCore.loadDescriptor(PluginManagerCore.java:714)
	at com.intellij.ide.plugins.PluginManagerCore.loadDescriptors(PluginManagerCore.java:912)
	at com.intellij.ide.plugins.PluginManagerCore.loadDescriptors(PluginManagerCore.java:1123)
	at com.intellij.ide.a.b.ar.b(ar.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1.a(MainImpl.java:50)
	at com.intellij.idea.MainImpl$1.start(MainImpl.java:85)
	at com.intellij.idea.StartupUtil.prepareAndStart(StartupUtil.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl.start(MainImpl.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.ide.plugins.PluginManager.lambda$start$0(PluginManager.java:75)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596)
	at com.intellij.openapi.util.SafeStAXStreamBuilder.build(SafeStAXStreamBuilder.java:115)
	at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:222)
	... 28 more`

**Comment by zielu** [comment]
Cannot reproduce
