### ISSUE TITLE
正常使用的过程中会出现下面的报错

### ISSUE THREAD

**Issue by cuianbing** [zielu/SVNToolBox#32]
Should be called at least in the state COMPONENTS_REGISTERED, the current state is: LAF_INITIALIZED
Current violators count: 1

java.lang.Throwable
	at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:56)
	at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:52)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:411)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:394)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:20)
	at com.intellij.ide.plugins.PluginUtil.getInstance(PluginUtil.java:11)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:43)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:28)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:36)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:36)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt)
	at zielu.svntoolbox.SvnToolBoxApp.<clinit>(SvnToolBoxApp.java:39)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:288)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:194)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:157)
	at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:93)
	at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt:379)
	at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
	at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:376)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.MainImpl$1.proceed(MainImpl.java:104)
	at com.intellij.ide.a.m.ap.proceed(ap.java:90)
	at com.intellij.ide.a.m.ao.b(ao.java:260)
	at com.intellij.ide.a.m.a4.b(a4.java:276)
	at com.intellij.ide.a.m.a4.c(a4.java:169)
	at com.intellij.ide.a.m.a4.a(a4.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.MainImpl.start(MainImpl.java:96)
	at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:289)
	at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:233)
	at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:47)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by zielu** [comment]
Hi, could you specify IDE and it's version ?

**Comment by zielu** [comment]
Fixed in 202.0.0
